### ISSUE TITLE
Performance ?

### ISSUE THREAD

**Issue by ganarajpr** [adobe-research/fondue#14]
I was trying to instrument my project ( https://github.com/ganarajpr/dhi-frontend ) which is a simple angular based application (you should be able to easily reproduce this using bower install and then using a http-server). 

The thing I noticed was that the application became incredibly slow when run through the instrumented. I wrote my own proxy server ( used fondue-middleware ). The files are getting served fine with all the trace information but like I mentioned earlier the app runs incredibly slow ( so much so that the processor is doing a lot of work! ). Is there some mechanism to speed this up ? I tried loading the same app with theseus extension from brackets and it is slightly faster (worse in performance as expected but not as bad as the other one).

Is there some way I can speed things up ? Are you doing any tricks in theseus to speed things up ?

**Comment by alltom** [comment]
The biggest speed-ups come from instrumenting as few files as possible. The mechanisms for this are listed in [Theseus's README](https://github.com/adobe-research/theseus):

* Node.js: Files with paths containing `node_modules` will not be instrumented.
* Chrome: Files requested with the URL parameter `theseus=no` (for example, `<script src="script.js?theseus=no" />`) will not be instrumented.
* Any file containing the (exact) string `/*theseus instrument: false */` will not be instrumented by Theseus.
* You can also use the `--theseus-exclude=filename` option with `node-theseus` (which also has some other options that you might find helpful).
